# Generated by Django 5.2.7 on 2025-10-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReStreamTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(help_text='Platform name (telegram, twitter, facebook, youtube)', max_length=50)),
                ('rtmp_url', models.URLField(help_text='RTMP URL for streaming')),
                ('stream_key', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Re-Stream Target',
                'verbose_name_plural': 'Re-Stream Targets',
                'db_table': 're_stream_target',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReStreamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='Source M3U/HLS URL')),
                ('rtmp_url', models.URLField(help_text='RTMP destination URL')),
                ('status', models.CharField(choices=[('Starting', 'Starting'), ('Running', 'Running'), ('Stopped', 'Stopped'), ('Error', 'Error')], default='Starting', max_length=20)),
                ('process_id', models.CharField(blank=True, help_text='FFmpeg process ID', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restream_sessions', to='stream_api.channel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stream_api.restreamtarget')),
            ],
            options={
                'verbose_name': 'Re-Stream Session',
                'verbose_name_plural': 'Re-Stream Sessions',
                'db_table': 're_stream_session',
                'ordering': ['-started_at'],
            },
        ),
    ]
